networks:
  default:
    driver: bridge
    name: roboshop-j

services:
  mongodb:
    image: cjagadeesh/mongodb:v1
    container_name: mongodb
    

  catalogue:
    image: cjagadeesh/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
    
  
  redis:
    image: redis:7
    container_name: redis
    


  user:
    image: cjagadeesh/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
    

  cart:
    image: cjagadeesh/cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
    

  frontend:
    image: cjagadeesh/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
    

